### PR TITLE
Improved modal dialogs

### PR DESCRIPTION
**Pull request by SjoerdB93**
Improves the "Add equation" window as discussed in issue #108 

image

Feedback welcome, I'm particularly not really sure yet about the margins to use everywhere.

### CODE REVIEW

**Comment by cmkohnen** [comment]
This doesn't run on my machine:
 ` File "/app/share/graphs/graphs/preferences.py", line 35, in check_config
   config = utilities.remove_unused_config_keys(config, template)
TypeError: remove_unused_config_keys() missing 1 required positional argument: 'template'`

**Comment by SjoerdB93** [comment]
Hmm, interesting. Seemed to work here. Can't find a remove_unused_config_keys without positional argument being given.

I've merged the current main branch into this PR again, maybe something got out of wack the previous time I did this. Try again with the latest commit maybe.

**Comment by cmkohnen** [comment]
Yeah I've found the reason, this is a thing in all other open PRs

**Comment by SjoerdB93** [comment]
Changed the above two dialog's confirm button to a pill as well to match the new style of "add equation"

image
image

**Comment by SjoerdB93** [comment]
Changed the margins a bit, also in the other modal dialogs. 
Removed the label as well for the other dialogs, to be consistent with "add equation". Feedback is welcome either way :)

image

image

**Comment by SjoerdB93** [comment]
I now put the information with more information about the Transform Window in an ExpanderRow, however the window doesn't resize back when I collapse it again. Not sure if this is a behaviour that's wanted. See video either way.

[Screencast from 2023-02-09 08-59-21.webm](https://user-images.githubusercontent.com/68477016/217752010-1f8df920-5940-4ba0-a147-f01619170ef8.webm)

**Review by cmkohnen — APPROVED** [review]

**Comment by cmkohnen** [comment]
I'd suggest just leaving the text for the transform window always visible. It is supposed to be for advanced uses anyway and doesn't really hinder the experience in my opinion. Having it under the two entry rows is quite a good change. Another solution would be to add a "?" button into the headerbar, which then opens either another dialogue or a AdwLeaflet showing this text

**Comment by SjoerdB93** [comment]
Yeah I think I'll move it back to always visible for now. Longer term it needs to be revamped a bit with some more proper documentation. There I'd like to have some specific examples, and perhaps activate scipy tools as well.

Right now it imports numpy as * for that specific module. Which is why I had this module as a seperate py file, as I don't want to do blank * imports in the rest of the code for obvious reasons. However, I didn't want users to have to write np.sin(X) to do a sine, hence the * import for numpy. I could add scipy to that mix with a single line of code, but it wouldn't surprise me if some functions overlap. So for scipy I was thinking to have it import scipy as sp, and explain that in documentation at one point. 

But again, that's future ideas that are beyond the scope of this PR, which is just about the UI design. For now having it as always visible would be fine I think (or at least better than having the window expand, and not go back to the original size as in the video). And then when we expand the documentation of it, we can tuck it away in a different widget. (We could just add a link, but I'm not always a fan of locking documentation away behind internet access)

I like the idea of putting it in an AdwLeaflet or something similar. Not sure about a new dialog. I've thought about that as well, but I didn't want a cascade of several dialogs popping up. Even though it is kinda pragmatic, it doesn't feel super nice design-wise.

**Comment by SjoerdB93** [comment]
Current version

image

**Pull request merged**
