### PR TITLE
Add "Save as project" functionality

### PR DESCRIPTION
**Pull request by SjoerdB93**
This adds the "Save Project" functionality as discussed in issue #99. See video at the bottom.

Feedback welcome. I think we may need to add a separator in the menu, but I'm not 100% sure. Also, I feel like the `graphs.py ` file is maybe becoming a bit bloated. Maybe some functions should be moved to a different new file to have a more clear categorisation. But I haven't looked into that at all, perhaps all functions do fit the same category (something like "core functionality" should be there I guess). 

Also as of now, it saves the project without any extension. In principle file extensions are kinda meaningless and mostly just guidelines, but it could be worthwhile to give it some custom extension, (e.g. .graphs) so that it's easy to find and filter them from the "open file" dialog when opening a project.

The implementation of the feature is relatively simple. Basically when saving it, it saves everything as a single dictionary containing two keys. project["data"] contains all data itself (which is a dictionary), and project["plot_settings"] contains the plot settings (which is an object in the PlotSettings class) that are used to set the plot settings from that session.

I did add a `color` attribute to the data objects, as this information was otherwise not stored in the project file meaning that information was lost when saving/loading projects. Now when loading data from this project file, it uses this attribute to give the color picker the appropriate colour. When plotting the data, it then takes the color of the color picker as a reference for which colour to use (just like it was before, so that part hasn't changed).

[Screencast from 2023-02-06 10-08-25.webm](https://user-images.githubusercontent.com/68477016/216932445-235cbc44-9363-4921-8afd-5d6218856330.webm)

### CODE REVIEW

**Comment by SjoerdB93** [comment]
Regarding the markers dissapearing when choosing tri_down, apparently that's a bug. The way I implemented this marker list, is just that I ask Matplotlib for all options and populate the chooser with those options. (Same is done with the graph style sheets, hence the weird naming convention there)

However the tri_direction series seem broken, and it can't set it to those values (hence it going back to "point") for some reason. From the name they seem identical to triangle_direction though. Maybe it's best if we set these values by hand instead of dynamically filling this list based on the matplotlib options.

**Comment by SjoerdB93** [comment]
I think at the least we should rename "Save project" option to "Export project", again to remain consistent with the naming of the other options.

**Comment by cmkohnen** [comment]
Looks nice, will take a look when I'm on my PC

**Comment by cmkohnen** [comment]
This seems to work rather nicely. I do not know much about the pickle module, so this might be a redundant question:
Does this scale with adding new options? I think we kind of need a system that checks, if a queried value is actually present in the format and load default if necessary. E. g. adding a plot setting which is queried on load might result in bugs, if trying to load a project from a previous version. on that note we might want to store the version, the project was generated in too.

**Comment by SjoerdB93** [comment]
So basically what the module does is save and load entire Python objects into a regular file. So in this case, I put both `self.plot_settings` and `self.datadict` into a dictionary, which I save using the Pickle module. Then when loading it, I get this stored dictionary with my objects, and can access them using the key I gave to it. Adding the current version number of Graphs is probably a good idea, if only for troubleshooting in the future. This is also quite trivial by simply adding `version` into this dictionary.

Regarding issues in the future. It simply loads `self.datadict` and `self.plot_settings` as-is from the previous session. So if new attributes are added to either the data set or plot_settings, we will probably run into an AttributeError. So I agree that there should be a system in place that fixes that. Perhaps something similar to what we do with the config file in preferences, that just goes through the attributes in a template, and add it if it's missing from our actual object.

**Comment by cmkohnen** [comment]
Yeah, I think having the same system in place like checking for config is a good idea. One could use pythons [inspect](https://docs.python.org/3/library/inspect.html#inspect.getmembers) method.

**Comment by SjoerdB93** [comment]
Yes, it's good to have something in place to keep compatibility over the longer term.

I've changed the `data` object a bit, and moved some code to this class. Basically, the initial clipboard data and position are now generated in the init function. And `set_data_properties` is now a class specific function that is applied on the dataset. Import_settings is an optional argument that can be given. A new dataset can then be created using data_set = Data(self, xdata, ydata, import_settings). Where the import_settings is optional, if not given it will just take the default import_settings from the preferences.
This all reduces quite a bit of replication, as you no longer explictly have to create new clipboard data all the time, this is just done on init as it should be.

I was thinking of using attributes that are present in the data objects to generate new Data objects when importing the data. This way, we explicitly use the same template/Class as for regularly newly added files. This doesn't stop the necessity of such a key synchronization as we have in preferences I think (definitely not for import_settings), but it should be a bit more robust. Will take a look at an implementation later.

**Comment by SjoerdB93** [comment]
This should work, but I should test it a bit more thoroughly probably. 
Also, I may want to add some separator in the menu...

**Comment by SjoerdB93** [comment]
I also changed the variable name id to key as id conflicts with a built-in Python function.
Also removed the dataclass decorator in Data as it lead to some troubles, basically the attributes that aren't defined during init are never assigned and therefore cannot be copied over. Figured it's probably best to define this during init instead.

**Review by cmkohnen — APPROVED** [review]

**Pull request merged**
