### PR TITLE
view menu improvements

### PR DESCRIPTION
**Pull request by cmkohnen**
Well, this was a chore...
After finally understanding the mechanics behind Menu states (no thanks to documentation or other projects using this),
the view menu now functions like @bertob suggested in https://github.com/SjoerdB93/Graphs/issues/60

### CODE REVIEW

**Comment by cmkohnen** [comment]
Well after reading https://github.com/SjoerdB93/Graphs/issues/60#issuecomment-1416300754 I wonder, if it would be nicer to have four toggles for each axis, like currently in settings.

**Comment by SjoerdB93** [comment]
> Well after reading [#60 (comment)](https://github.com/SjoerdB93/Graphs/issues/60#issuecomment-1416300754) I wonder, if it would be nicer to have four toggles for each axis, like currently in settings.

Yes, now I think of that, that is probably a lot more intuitive than one button that toggles two opposing axes at once.

**Comment by cmkohnen** [comment]
Changed that, now picks up the preferences options too

**Comment by SjoerdB93** [comment]
Sounds good, I'll check it out tomorrow when I'm at my computer again.

**Review by SjoerdB93 — APPROVED** [review]

**Pull request merged**
