### PR TITLE
Transform discard

### PR DESCRIPTION
**Pull request by cmkohnen**
based on https://github.com/SjoerdB93/Graphs/pull/144

Adds ability to discard unselected data, when using transform

### CODE REVIEW

**Comment by SjoerdB93** [comment]
There were quite a bunch of features broken with this PR (most of the operations). I started digging into a a few of them, and solved some but not all this morning but didn't have the time to fix all I could find. I've pushed those to a different branch: https://github.com/SjoerdB93/Graphs/tree/pr145_bugfixes_wip

**Comment by cmkohnen** [comment]
Oh, that is a massive oversight on my end. These were introduced somewhere in https://github.com/SjoerdB93/Graphs/pull/144. Some of these I haven't given much thought whilst changing to be honest.

**Comment by SjoerdB93** [comment]
Just to add on previous comment, as I didn't respond to this PR itself. I do like this, in particular how this button appears contextually. That's a nice touch.

**Comment by SjoerdB93** [comment]
This works well now for me!

**Review by SjoerdB93 — APPROVED** [review]

**Pull request merged**
