### PR TITLE
use unique identifiers for data management

### PR DESCRIPTION
**Pull request by cmkohnen**
This allows for multiple items / files bearing the same visual name to be displayed simultaneously without overriding each other. I'm trying to update the config to implement changes discussed in https://github.com/SjoerdB93/Graphs/issues/26#issuecomment-1399338374 
grafik
Still needs testing, as I haven't tried every option yet

### CODE REVIEW

**Comment by SjoerdB93** [comment]
Hey,

This is looking great! 
I was planning to add this concept of using an identifier instead of a filename later today, or potentially tomorrow, but you were really fast :)

I've played around with it, and it does seem to work well. I noticed the "delete" hotkey didn't work, as it wants both the filename and the id. I fixed this in the latest commit, now it just takes the filename from the data object instead, which is probably better anyway.

**Comment by cmkohnen** [comment]
I have now added four options:

- auto-rename appends a (1), (2), etc. (default for now)
- keep doesn't do anything and just adds the file / equation
- ignore skips the file (giving a toast)
- override overrides any existing file with that name

**Comment by SjoerdB93** [comment]
Yes, that's a nice set of options. I like the addition of the override option as well, that's nice to have. 
I now fixed the delete button now as well, and everything seems good to go.

Only thing I'm unsure about is whether we should use more descriptive labels for the options. Either just by changing the keys to more descriptive ones directly, or rename the dropdown options and couple those to the keys in-code. An option such as "keep" for example may not be directly obvious for a user what it does. Something in the vicinity of: 
"Auto-rename duplicate files"
"Add duplicate file" 
"Ignore duplicate files"
"Override duplicate files"

Not 100% sold on those labels (maybe "override existing files" would be more correct), but I was thinking of something in that vain.

**Comment by cmkohnen** [comment]
I agree, having them this short is a bit unintuitive

**Review by SjoerdB93 — APPROVED** [review]

**Pull request merged**
