### PR TITLE
Change to 20 px color button

### PR DESCRIPTION
**Pull request by SjoerdB93**
With a color chooser the size of 20 px as disccused in issue #54. Also contains a fix to how the next color in the cycle is chosen. Behaviour is a same, but it fixes a bug where it would choose existing color anyway whenever the colorchooser widget has been activated for that particular sample. 

20 px:
image

Here's the color picker at two larger sizes as well, just for reference:

25 px:
image

30 px:
image

### CODE REVIEW

**Comment by cmkohnen** [comment]
Uhm, you seem to have included all _build files and none of the actual source

**Comment by SjoerdB93** [comment]
> Uhm, you seem to have included all _build files and none of the actual source

Woops, that's sloppy. Should be fixed now.

**Comment by cmkohnen** [comment]
I quite like the 25px version

**Comment by SjoerdB93** [comment]
Yeah, I think most are an improvement. For what it's worth, your PR #97 was not in vain, as this one is a derivative of that branch. I couldn't figure out how to resize a GtkButton to smaller sizes, but using an icon as a work-around (which is what this does) worked perfectly.

Just as a quick references, here's some of the options:
A = 20 px
B = 25 px
C = Fill bucket
D = 30 px
E = GNOME Color Picker
bild

I kinda like the circular dot, especially version A or B. Either are an improvement of the big dot in the current main branch.
But I do see an argument in using E as well, as @mossymossmoss mentions in issue #34 this is the standard GNOME widget for the Color Picker.

**Comment by SjoerdB93** [comment]
So I found the following passage in the GNOME HIG:

>GTK and Adwaita can be used as the basis for custom UI elements, which are not included in the GNOME platform. The appearance of preexisting widgets can also be customized.
>
>As a general rule, it is better to keep the amount of this custom styling to a minimum, as this will reduce maintenance overhead, >will reduce bugs, and will help to ensure compatibility with accessibility and internationalization features.

So I'm tempted to merge this with a pixel size of 20 px. But I'll wait for @cmkohnen before force-merging this :)

**Comment by cmkohnen** [comment]
I think I'm happy with either 20px (A) or 25px (B), with a slight tendency towards 20px as well, so that it fits with the close button right next to it.

**Review by cmkohnen — APPROVED** [review]

**Pull request merged**
