### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by cmkohnen**

### CODE REVIEW

**Comment by cmkohnen** [comment]
Updating CI might fix failing builds

**Comment by cmkohnen** [comment]
Nevermind, having them up to date is a benefit either way

**Comment by SjoerdB93** [comment]
For some reason it keeps giving a 404 on the Gnome sdk on aarch64.  Error: Failed to install org.gnome.Sdk: While pulling runtime/org.gnome.Sdk/aarch64/43 from remote flathub: Server returned HTTP 404

Flathub's buildbot works fine, so the application itself builds fine on aarch64 in the real world. Not sure what's wrong here.

**Review by SjoerdB93 — APPROVED** [review]
x86 builds fine though, so no use on staying with old versions here.

**Comment by SjoerdB93** [comment]
In the meantime I'm considering if we should just disable aarch64 in this workflow, and test-build those with flathub releases. When pushing this to flathub, it builds for both x86 and aarch64 before I can merge it in the main manifest. There it works fine.

https://github.com/flathub/se.sjoerd.Graphs/pull/2

**Pull request merged**
